name: Update Contributors List

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributors and Update README
        run: |
          # Fetch contributors from GitHub API
          CONTRIBUTORS_LIST=$(curl -s https://api.github.com/repos/hypecode-tech/blogs/contributors | \
            jq -r '.[] | "- [\(.login)](https://github.com/\(.login))"')

          # Update README.md
          sed -i '/<!-- BEGIN CONTRIBUTORS LIST -->/,/<!-- END CONTRIBUTORS LIST -->/d' README.md
          sed -i "/#### Katkıda bulunanlar/a \\\n<!-- BEGIN CONTRIBUTORS LIST -->\n${CONTRIBUTORS_LIST}\n<!-- END CONTRIBUTORS LIST -->" README.md
          
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update CONTRIBUTORS list in README.md'
          add: 'README.md'
