name: Update Contributors List

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributors from GitHub
        id: fetch-contributors
        run: |
          # Fetch contributors from GitHub API and format them
          CONTRIBUTORS_LIST=$(curl -s https://api.github.com/repos/hypecode-tech/blogs/contributors | \
            jq -r '.[] | "- [\(.login)](https://github.com/\(.login))"' | \
            awk '{print "  " $0}')

          # Save the list as an environment variable
          echo "CONTRIBUTORS_LIST<<EOF" >> $GITHUB_ENV
          echo "$CONTRIBUTORS_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          # Read current README.md
          README_CONTENT=$(cat README.md)

          # Prepare the new README content by replacing the contributors section
          NEW_README_CONTENT=$(echo "$README_CONTENT" | awk -v list="$CONTRIBUTORS_LIST" '
            BEGIN {p=1}
            /<!-- BEGIN CONTRIBUTORS LIST -->/ {print; print list; p=0}
            /<!-- END CONTRIBUTORS LIST -->/ {p=1}
            p')

          # Write the updated content back to README.md
          echo "$NEW_README_CONTENT" > README.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update CONTRIBUTORS list in README.md'
          add: 'README.md'
