name: Katkıda bulunanlar listesi güncelleme

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributors from GitHub
        id: fetch-contributors
        run: |
          # Fetch contributors from GitHub API and format them
          CONTRIBUTORS_LIST=$(curl -s https://api.github.com/repos/hypecode-tech/blogs/contributors | \
            jq -r '.[] | "- [\(.login)](https://github.com/\(.login))"' | \
            awk '{print "  " $0}')

          # Set the contributors list as an output
          echo "CONTRIBUTORS_LIST<<EOF" >> $GITHUB_ENV
          echo "$CONTRIBUTORS_LIST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          # Backup the original README.md
          cp README.md README.md.bak

          # Use awk to replace the old contributors list with the new one
          awk -v list="$CONTRIBUTORS_LIST" '
            BEGIN { inside=0 }
            /<!-- BEGIN CONTRIBUTORS LIST -->/ { inside=1; print; next }
            /<!-- END CONTRIBUTORS LIST -->/ { inside=0; print list; print; next }
            { print }
          ' README.md.bak > README.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update CONTRIBUTORS list in README.md'
          add: 'README.md'
