name: Update Contributors List

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributors and Update README
        run: |
          # Fetch contributors from GitHub API
          CONTRIBUTORS_LIST=$(curl -s https://api.github.com/repos/hypecode-tech/blogs/contributors | \
            jq -r '.[] | "- [\(.login)](https://github.com/\(.login))"' | \
            awk '{print "  " $0}')

          # Create a temporary file to store the updated README
          awk -v list="$CONTRIBUTORS_LIST" '
            BEGIN { inside=0 }
            /<!-- BEGIN CONTRIBUTORS LIST -->/ { inside=1; print; next }
            /<!-- END CONTRIBUTORS LIST -->/ { inside=0; print list; print; next }
            { print }
          ' README.md > README.md.tmp

          # Replace the old README with the updated one
          mv README.md.tmp README.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update CONTRIBUTORS list in README.md'
          add: 'README.md'
