name: Update Blog Links in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install franc-min for language detection
        run: |
          npm install franc-min

      - name: Update Blog Links
        run: |
          # JavaScript dosyasını oluştur
          cat << 'EOF' > update-readme.js
          const fs = require('fs');
          const path = require('path');
          const franc = require('franc-min'); // Dil tespit kütüphanesi

          const baseDir = '.'; // Repo kök dizini
          const readmePath = path.join(baseDir, 'README.md');
          const baseUrlTr = 'https://hypecode.tech/blog';
          const baseUrlEn = 'https://hypecode.tech/en/blog';

          // Klasörleri oku
          const folders = fs.readdirSync(baseDir).filter((folder) => {
            const folderPath = path.join(baseDir, folder);
            return fs.statSync(folderPath).isDirectory() && folder !== '.github';
          });

          // Dil tespiti fonksiyonu
          const detectLanguage = (folder) => {
            const filePath = path.join(baseDir, folder, 'README.md');
            const fileContent = fs.readFileSync(filePath, 'utf-8');
            const lang = franc(fileContent); // Metni analiz et
            return lang === 'eng' ? 'en' : 'tr'; // Eğer dil İngilizce ise 'en', Türkçe ise 'tr'
          };

          // Link listesini oluştur
          const links = folders.map((folder) => {
            let language = detectLanguage(folder); // Dil tespiti
            let baseUrl = language === 'en' ? baseUrlEn : baseUrlTr;
            let link = `${baseUrl}/${folder}`;
            return `[${folder}](${link})`;
          });

          // README.md dosyasını oku
          const readmeContent = fs.readFileSync(readmePath, 'utf-8');
          const updatedReadme = readmeContent.replace(
            /### İçerik Listesi[\s\S]*?#### Katkıda bulunanlar/,
            `### İçerik Listesi\n\n${links.join('\n\n')}\n\n#### Katkıda bulunanlar`
          );

          // README.md dosyasını güncelle
          fs.writeFileSync(readmePath, updatedReadme, 'utf-8');
          console.log('README.md güncellendi!');
          EOF

          # JavaScript dosyasını çalıştır
          node update-readme.js

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update blog links in README.md"
          git push
