name: Update Blog Links in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Blog Links
        run: |
          # JavaScript dosyasını oluştur
          cat << 'EOF' > update-readme.js
          const fs = require('fs');
          const path = require('path');

          const baseDir = '.'; // Repo kök dizini
          const readmePath = path.join(baseDir, 'README.md');
          const baseUrl = 'https://hypecode.tech/blog';

          // Slug'u unslug'a çeviren fonksiyon
          const unslug = (slug) => {
            return slug
              .replace(/-/g, ' ')
              .replace(/\b\w/g, (char) => char.toUpperCase());
          };

          // Klasörleri oku
          const folders = fs.readdirSync(baseDir).filter((folder) => {
            const folderPath = path.join(baseDir, folder);
            return fs.statSync(folderPath).isDirectory() && folder !== '.github';
          });

          // Link listesini oluştur
          const links = folders.map((folder) => {
            const title = unslug(folder);
            const link = `${baseUrl}/${folder}`;
            return `[${title}](${link})`;
          });

          // README.md dosyasını oku
          const readmeContent = fs.readFileSync(readmePath, 'utf-8');
          const updatedReadme = readmeContent.replace(
            /### İçerik Listesi[\s\S]*?#### Katkıda bulunanlar/,
            `### İçerik Listesi\n\n${links.join('\n\n')}\n\n#### Katkıda bulunanlar`
          );

          // README.md dosyasını güncelle
          fs.writeFileSync(readmePath, updatedReadme, 'utf-8');
          console.log('README.md güncellendi!');
          EOF

          # JavaScript dosyasını çalıştır
          node update-readme.js

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update blog links in README.md"
<<<<<<< HEAD
          git push
=======
          git push
>>>>>>> 26f67d5e00b9839c9e946f8a99a4d5b693db9261
